http:
  routers:
    outline:
      rule: "Host(`outline.chillpickle.org`)"
      entryPoints: [websecure]
      service: outline

    traefik-dashboard:
      rule: "Host(`traefik.tcom.chillpickle.org`)"
      entryPoints: [websecure]
      service: api@internal
      middlewares: [dashboard-auth]

    chillang-api:
      rule: "Host(`api.chillang.chillpickle.org`)"
      entryPoints: [websecure]
      service: chillang-api

  services:
    outline:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8089"

    chillang-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8091"
