http:
  routers:
    outline:
      rule: "Host(`outline.chillpickle.org`)"
      entryPoints: [websecure]
      service: outline

    chillang-api:
      rule: "Host(`api.chillang.chillpickle.org`)"
      entryPoints: [websecure]
      service: chillang-api

    dashy:
      rule: "Host(`dash.chillpickle.org`)"
      entryPoints: [websecure]
      service: dashy

    todo-api:
      rule: "Host(`todo.chillpickle.org`)"
      entryPoints: [websecure]
      service: todo-api

  services:
    outline:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8089"

    chillang-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8091"

    dashy:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8092"

    todo-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8093"
