http:
  routers:
    chillang-api:
      rule: "Host(`api.chillang.chillpickle.org`)"
      entryPoints: [websecure]
      service: chillang-api

    story-api:
      rule: "Host(`story.chillpickle.org`)"
      entryPoints: [websecure]
      service: story-api

    grafana:
      rule: "Host(`grafana.chillpickle.org`)"
      entryPoints: [websecure]
      service: grafana

    n8n:
      rule: "Host(`n8n.chillpickle.org`)"
      entryPoints: [websecure]
      service: n8n

    traefik-dashboard:
      rule: "Host(`traefik.tcom.chillpickle.org`)"
      entryPoints: [websecure]
      service: api@internal
      middlewares:
        - dashboard-auth

  services:
    chillang-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8091"

    story-api:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:8093"

    grafana:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:3001"

    n8n:
      loadBalancer:
        servers:
          - url: "http://host.docker.internal:5678"
