services:
  stories-api:
    image: ghcr.io/chill-pickle/stories-api:latest
    container_name: stories_api
    restart: unless-stopped
    ports:
      - "8093:8093"
    volumes:
      - stories_data:/app/data
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  stories_data:
